name: arcgis_llm
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # ArcGIS Pro packages (arcpy 3.4) are already included in the cloned environment
  # GIS packages
  - fiona=1.9.5
  - rasterio=1.3.9
  # Additional conda packages
  - pip
  - pip:
    # Pip packages are specified in requirements.txt
    - -r requirements.txt 